name: Deploy to Tencent Cloud COS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      # Step 3: Download and install COSCLI (Linux version)
      - name: Install coscli
        run: |
          curl -L https://github.com/tencentyun/coscli/releases/download/v1.0.2/coscli-v1.0.2-linux-amd64 -o /tmp/coscli
          chmod +x /tmp/coscli
          sudo mv /tmp/coscli /usr/local/bin/coscli

      # Step 4: Configure coscli
      - name: Configure coscli
        run: |
          coscli config -u <<EOF
          [common]
          secret_id = ${{ secrets.TENCENT_SECRET_ID }}
          secret_key = ${{ secrets.TENCENT_SECRET_KEY }}
          region = ap-guangzhou
          EOF

      # Step 5: Upload to Tencent Cloud COS
      - name: Upload to Tencent COS
        run: |
          coscli sync ./dist cos://your-bucket-name/

      # Step 6: Post Checkout code (optional, clean up if needed)
      - name: Post Checkout code
        run: echo "Deployment complete."