name: Deploy to Tencent COS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Secrets
      run: |
        if [ -z "${{ secrets.TENCENT_SECRET_ID }}" ]; then
          echo "TENCENT_SECRET_ID is missing or not set!"
          exit 1
        else
          echo "TENCENT_SECRET_ID is set!"
        fi

        if [ -z "${{ secrets.TENCENT_SECRET_KEY }}" ]; then
          echo "TENCENT_SECRET_KEY is missing or not set!"
          exit 1
        else
          echo "TENCENT_SECRET_KEY is set!"
        fi

    - name: Install COSCLI
      run: |
        curl -o coscli.zip https://github.com/tencentyun/coscli/releases/download/v0.13.1/coscli-linux-amd64.zip
        unzip coscli.zip -d coscli
        sudo mv coscli/coscli /usr/local/bin/

    - name: Configure COSCLI
      run: |
        mkdir -p ~/.coscli
        echo "
        {
          \"secret_id\": \"$TENCENT_SECRET_ID\",
          \"secret_key\": \"$TENCENT_SECRET_KEY\",
          \"bucket\": \"blog-index-1309745445\",
          \"region\": \"ap-shanghai\"
        }
        " > ~/.coscli/config
      env:
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}

    - name: Upload to COS
      run: |
        coscli sync ./ cos://blog-index-1309745445/ --delete