name: Deploy to Tencent Cloud COS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装依赖工具
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y curl unzip

    # 下载并安装 coscli
    - name: Install coscli
      run: |
        curl -o coscli.zip -L https://github.com/tencentyun/coscli/releases/download/v1.0.2/coscli-linux-amd64.zip
        unzip -o coscli.zip -d /tmp
        sudo mv /tmp/coscli /usr/local/bin/
        rm coscli.zip

    # 配置 coscli
    - name: Configure coscli
      run: |
        coscli config add -a ${{ secrets.COS_SECRET_ID }} \
          -s ${{ secrets.COS_SECRET_KEY }} \
          -b ${{ secrets.COS_BUCKET }} \
          -r ${{ secrets.COS_REGION }}

    # 上传到腾讯云 COS
    - name: Upload to Tencent COS
      run: |
        coscli sync ./dist/ -r # 将本地 ./dist 目录的内容同步到 COS

    # 完成部署
    - name: Post Checkout code
      run: |
        echo "Deployment completed successfully."