name: Deploy to Tencent Cloud COS

on:
  push:
    branches:
      - master # 在 master 分支的提交触发工作流
  workflow_dispatch: # 手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装依赖工具
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y curl unzip

    # 下载并安装 coscli
    - name: Install coscli
      run: |
        curl -o coscli.zip -L https://github.com/tencentyun/coscli/releases/download/v1.0.2/coscli-linux-amd64.zip
        unzip coscli.zip
        mv coscli /usr/local/bin/

    # 配置 coscli
    - name: Configure coscli
      run: |
        coscli config add -a ${{ secrets.COS_SECRET_ID }} \
          -s ${{ secrets.COS_SECRET_KEY }} \
          -b ${{ secrets.COS_BUCKET }} \
          -r ${{ secrets.COS_REGION }}

    # 上传到腾讯云 COS
    - name: Upload to Tencent COS
      run: |
        coscli sync ./ dist/ -r # 将本地 ./dist 目录的内容同步到 COS

    # 清理步骤（可选）
    - name: Post Checkout code
      run: |
        echo "Deployment completed successfully."