name: Deploy to Tencent Cloud COS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install coscli
        run: |
          curl -L https://github.com/tencentyun/coscli/releases/download/v1.0.2/coscli-v1.0.2-linux-amd64 -o /tmp/coscli
          chmod +x /tmp/coscli
          sudo mv /tmp/coscli /usr/local/bin/coscli

      - name: Configure coscli
        run: |
          mkdir -p ~/.cos
          echo "common:
  secret_id: ${TENCENT_SECRET_ID}
  secret_key: ${TENCENT_SECRET_KEY}
  region: ap-shanghai
buckets:
  - name: blog-index-1309745445
    endpoint: cos.ap-shanghai.myqcloud.com" > ~/.cos/cos.yaml
          cat ~/.cos/cos.yaml

      - name: Upload to Tencent COS
        run: |
          echo "Uploading files to COS..."
          coscli sync ./dist cos://blog-index-1309745445/ --recursive --config-path ~/.cos/cos.yaml