name: Deploy to Tencent Cloud COS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          yarn install

      # Step 3: Build project
      - name: Build Project
        run: |
          yarn build

      # Step 4: Verify output folder
      - name: Verify output folder
        run: |
          if [ ! -d "./dist" ]; then
            echo "Error: dist folder does not exist. Please check your build process."
            exit 1
          fi

      # Step 5: Install coscli
      - name: Install coscli
        run: |
          curl -L https://github.com/tencentyun/coscli/releases/download/v1.0.2/coscli-v1.0.2-linux-amd64 -o /tmp/coscli
          chmod +x /tmp/coscli
          sudo mv /tmp/coscli /usr/local/bin/coscli

      # Step 6: Configure coscli
      - name: Configure coscli
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        run: |
          mkdir -p ~/.cos
          echo "[common]" > ~/.cos/cos.yaml
          echo "secret_id = ${TENCENT_SECRET_ID}" >> ~/.cos/cos.yaml
          echo "secret_key = ${TENCENT_SECRET_KEY}" >> ~/.cos/cos.yaml
          echo "region = ap-shanghai" >> ~/.cos/cos.yaml

      # Step 7: Upload to Tencent COS
      - name: Upload to Tencent COS
        run: |
          coscli sync ./dist cos://blog-index-1309745445/ --recursive

      # Step 8: Post-deployment message
      - name: Post Deployment
        run: echo "Deployment to Tencent COS completed."