name: Deploy to Tencent COS
on:
  push:
    branches:
      - main # 当main分支有推送时触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install coscmd
      run: |
        pip install coscmd
    - name: Configure coscmd
      run: |
        coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} -s ${{ secrets.TENCENT_SECRET_KEY }} -b blog-index-1309745445 -r ap-shanghai
    - name: Upload files to COS
      run: |
        coscmd upload -r dist/ cos://blog-index-1309745445/